// Generate spec/golden.json: the cross-language conformance vectors.
//
// The whole portability claim rests on this file. If the JS, C#, and GDScript
// evaluators agree on these cases, they agree on every input, because decide()
// is a fixed number of multiply-adds over a known layout.
//
// Regenerate with: node spec/make-golden.js

import { writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readFileSync } from 'node:fs';
import { randBrain, packBrain, unpackBrain, decide, explain, specHash, brainBytes, brainFitsBudget } from '../sdk/js/s1.js';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const spec = JSON.parse(readFileSync(join(root, 'games/arena/game.s1.json'), 'utf8'));

function mulberry(a) {
  return () => {
    a |= 0; a = (a + 0x6D2B79F5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function b64(bytes) {
  return Buffer.from(bytes).toString('base64');
}

// Deterministic feature cases that touch every feature slot and both signs.
function featureCases(n) {
  const rng = mulberry(0xC0FFEE);
  const cases = [];
  for (let i = 0; i < n; i++) {
    const f = [];
    for (let k = 0; k < spec.features.length; k++) f.push(Math.round((rng() * 2 - 1) * 1000) / 1000);
    cases.push(f);
  }
  // A few hand-written edge cases: all-zero, all-+1, all--1, alternating.
  cases.push(new Array(spec.features.length).fill(0).map((_, i) => i));
  cases.push(new Array(spec.features.length).fill(1));
  cases.push(new Array(spec.features.length).fill(-1));
  cases.push(spec.features.map((_, i) => (i % 2 ? 1 : -1)));
  return cases;
}

function vectorsFor(name, brain) {
  const packed = packBrain(brain);
  const u = unpackBrain(packed);
  const cases = [];
  const feats = featureCases(14);
  for (const f of feats) {
    for (const arch of [0, 1, 2]) {
      for (const ctx of u.gated ? [0, 1, 2, 3] : [0]) {
        const d = decide(u, f, arch, ctx);
        cases.push({
          f,
          arch,
          ctx,
          action: d.action,
          action_name: spec.actions[d.action],
          score: Math.round(d.score * 1e6) / 1e6,
        });
      }
    }
  }
  return { name, brain_b64: b64(packed), bytes: packed.length, n_features: u.nF, n_actions: u.nA, n_contexts: u.nC, n_archetypes: u.nArch, gated: u.gated, cases };
}

const brains = [];

// 1. A synthetic brain with a known pattern, so a failing evaluator is easy to
//    read: "retreat when hurt and pressured, otherwise advance".
const hand = {
  hash: specHash(spec),
  nF: spec.features.length, nA: spec.actions.length, nC: spec.contexts.length, nArch: spec.archetypes.length,
  gateCount: 4, gated: true,
  w: new Float32Array(spec.contexts.length * spec.actions.length * spec.features.length),
  archBias: new Float32Array(spec.archetypes.length * spec.actions.length),
  thresholds: new Float32Array([0.35, 0.15, -0.35, -0.1]),
  scale: new Float32Array(spec.features.length).fill(1),
  biasScale: 1,
  minDwellTicks: Math.round(spec.gate.min_dwell_s * spec.sim.tick_rate),
};
{
  const nF = hand.nF, nA = hand.nA;
  const set = (ctx, action, weights) => {
    for (let i = 0; i < nF; i++) hand.w[(ctx * nA + action) * nF + i] = weights[i] ?? 0;
  };
  const zero = new Array(nF).fill(0);
  for (let c = 0; c < hand.nC; c++) {
    set(c, 0, [...zero, -18, -6, 22, 6, -4, -14, -4, 4, 0, 6]);   // advance
    set(c, 1, [...zero, -8, -14, -6, 10, 0, 4, 10, 2, 0, 2]);    // hold
    set(c, 2, [...zero, 12, 8, 4, 10, 8, -2, 0, 0, 0, 0]);       // peek
    set(c, 3, [...zero, 40, 6, 36, -4, 18, 6, 0, 0, 0, -6]);     // retreat
    set(c, 4, [...zero, 6, -10, 0, 2, 6, 4, 8, -4, 0, 4]);       // rotate
    set(c, 5, [...zero, 4, 12, -14, 0, 0, 0, 0, 6, 30, 0]);      // use_ability
    set(c, 6, [...zero, -10, -2, 0, 40, 0, -4, 0, 0, 0, 0]);     // reload
  }
  for (let a = 0; a < hand.nArch; a++) hand.archBias.fill(0);
  hand.archBias[2 * hand.nA + 6] = 18; // snipers reload more
  hand.archBias[2 * hand.nA + 1] = -12;
}
brains.push(vectorsFor('handmade-gated', hand));

// 2. A random brain: catches implementations that assume weight magnitudes or
//    sign patterns.
const rnd = randBrain(spec, { gated: true, rng: mulberry(99) });
rnd.minDwellTicks = hand.minDwellTicks;
brains.push(vectorsFor('random-gated', rnd));

// 3. The tiny ungated tier from disk, if present.
try {
  const tiny = unpackBrain(new Uint8Array(readFileSync(join(root, 'games/arena/brains/tiny.s1b'))));
  brains.push(vectorsFor('tiny-ungated', tiny));
} catch { /* generated by the trainer on first run */ }

// 4. The shipped champion, if present: proves the vector file covers the brain
//    that is actually live.
try {
  const champ = unpackBrain(new Uint8Array(readFileSync(join(root, 'games/arena/brains/champion.s1b'))));
  brains.push(vectorsFor('champion', champ));
} catch { /* no champion yet */ }

const out = {
  s1: 1,
  spec_id: spec.id,
  spec_hash: specHash(spec).toString(16),
  feature_names: spec.features,
  action_names: spec.actions,
  context_names: spec.contexts,
  archetype_names: spec.archetypes,
  budget_bytes: spec.budget_bytes,
  note: 'Regenerate with `node spec/make-golden.js`. Runners in every language must reproduce `action` exactly and `score` to 1e-6.',
  brains: brains.map((b) => ({ ...b, within_budget: brainFitsBudget(unpackBrain(Buffer.from(b.brain_b64, 'base64')), spec), bytes: brainBytes(unpackBrain(Buffer.from(b.brain_b64, 'base64'))) })),
};

writeFileSync(join(here, 'golden.json'), JSON.stringify(out, null, 1));
console.log(`wrote spec/golden.json: ${out.brains.length} brains, ${out.brains.reduce((s, b) => s + b.cases.length, 0)} cases`);
for (const b of out.brains) console.log(`  ${b.name}: ${b.bytes} B, ${b.cases.length} cases, within_budget=${b.within_budget}`);